repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tfsec
      - id: terraform_validate
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
